# TODO - reorganize
# astro-portfolio
version: "3"
services:
  app:
    image: rickjhoppe/astro-portfolio:latest
    restart: on-failure:3
    container_name: astro-portfolio
    ports:
      - "127.0.0.1:4321:4321"
    volumes:
      - sqlite-data:/data
      - meta-data:/app/data/meta
      - db-data:/app/data/db
volumes:
  sqlite-data:
  meta-data:
  db-data:

# ntfy
version: "2.3"
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=America/New_York   # optional: set desired timezone
    user: 1003:1003 # replace with the user/group or uid/gid
    volumes:
      - ./cache:/var/cache/ntfy
      - ./config:/etc/ntfy
      - ./db:/var/lib/ntfy/
    ports:
      - 8000:80 # exposed on port 8000 (you can change it)
    restart: unless-stopped

# dozzle
version: "3"
services:
  app:
    container_name: dozzle
    image: amir20/dozzle:v8.11.7
    restart: on-failure:3
    environment:
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:8888:8080"

# watchtower
version: '3'
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - TZ=America/New_York
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_TIMEOUT=60s
      - WATCHTOWER_LOG_FORMAT=pretty
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=ntfy://ntfy.rjhoppe.dev/[your-topic-here]?scheme=https
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

# glances
version: "3.9"
services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    pid: host
    restart: on-failure:3
    ports:
      - "127.0.0.1:61208:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: America/New_York
      GLANCES_OPT: -w

# mumble
version: '3.8'
services:
    mumble-server:
        image: mumblevoip/mumble-server:latest
        container_name: mumble
        hostname: murmur
        restart: on-failure:3
        user: root
        volumes:
            - type: bind
              source: ./data/mumble
              target: /data
              read_only: false
            - type: bind
              source: /etc/letsencrypt/archive/mumble.rjhoppe.dev
              target: /certificates
              read_only: false
        environment:
            MUMBLE_CONFIG_SSL_CERT: /certificates/fullchain1.pem
            MUMBLE_CONFIG_SSL_KEY: /certificates/privkey1.pem
            MUMBLE_CONFIG_USERS: 10 # Max amount of users that can connect at the same time
            MUMBLE_CONFIG_USERSPERCHANNEL: 10  # Means unlimited if zero
            MUMBLE_CONFIG_WELCOME_TEXT: ""
            MUMBLE_CONFIG_USERNAME: '[ -=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.]+'
            MUMBLE_CONFIG_CHANNELNAME: '[ \\-=\\w\\#\\[\\]\\{\\}\\(\\)\\@\\|\\%\\'']+'
            MUMBLE_SUPERUSER_PASSWORD: "Test"
            MUMBLE_REGISTERSERVER: 0
            MUMBLE_VERBOSE: 1
        ports:
            - 64738:64738
            - 64738:64738/udp

# mumble env vars to pass in
MUMBLE_SUPERUSER_PASSWORD

# ntfy
version: '3'
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command: serve
    environment: 
      - TZ=America/New_York
    # Left side refers to the path on the host
    # Right side refers to the path on the container
    volumes:
      # Maps cache dir from host to container
      - /data/ntfy/cache:/var/cache/ntfy
      # Maps config dir from host to container
      - /data/ntfy/config:/etc/ntfy
    ports:
      - 127.0.0.1:7200:80
    restart: on-failure:3

# umami
version: "3"
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@umami-db:5432/${POSTGRES_DB}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SECRET}
    depends_on:
      umami-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - curl http://localhost:3000/api/heartbeat
      interval: 5s
      timeout: 5s
      retries: 5
  umami-db:
    image: postgres:15-alpine
    container_name: umami-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./umami-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
  umami-db-backup:
    container_name: umami-db-backup
    image: tiredofit/db-backup
    volumes:
      - ./backups:/backup
    environment:
      DB_TYPE: postgres
      DB_HOST: umami-db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_BACKUP_INTERVAL: 720
      DB_CLEANUP_TIME: 72000
      #DB_BACKUP_BEGIN: 1
      CHECKSUM: SHA1
      COMPRESSION: GZ
      CONTAINER_ENABLE_MONITORING: false
    depends_on:
      umami-db:
        condition: service_healthy
    restart: unless-stopped
