# TODO - reorganize
# astro
version: "3"
services:
  app:
    image: rickjhoppe/astro-portfolio:latest
    container_name: astro-portfolio
    ports:
      - "127.0.0.1:4321:4321"
    volumes:
      - sqlite-data:/data
      - meta-data:/app/data/meta
      - db-data:/app/data/db

volumes:
  sqlite-data:
  meta-data:
  db-data:

# dozzle
version: "3"
services:
  app:
    container_name: dozzle
    image: amir20/dozzle:v8.11.7
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:8888:8080"

# watchtower
version: '3'
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_REVIVE_STOPPED=true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

# glances
version: "3.9"
services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    pid: host
    restart: on-failure:3
    ports:
      - "127.0.0.1:61208:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      GLANCES_OPT: -w

# mumble
version: '3.3'
services:
    mumble-server:
        image: mumblevoip/mumble-server:v1.4.230-6
        container_name: murmur
        hostname: murmur
        restart: always
        volumes:
            - type: bind
              source: ./data/mumble
              target: /data
              read_only: false
            - type: bind
              source: ./data/certificates
              target: /certificates
              read_only: false
        environment:
            MUMBLE_CONFIG_SSL_CERT: /certificates/cert.pem
            MUMBLE_CONFIG_SSL_KEY: /certificates/key.pem
            MUMBLE_SUPERUSER_PASSWORD: <your-superuser-password>
            MUMBLE_CONFIG_SERVERPASSWORD: <your-server-password>
            MUMBLE_CONFIG_USERS: 10 # Max amount of users that can connect at the same time
            MUMBLE_CONFIG_USERSPERCHANNEL: 10  # Means unlimited if zero
            MUMBLE_CONFIG_WELCOMETEXT: "Oh god, not this fucking guy"
            MUMBLE_CONFIG_ALLOWHTML: true
        ports:
            - 127.0.0.1:64738:64738/tcp
            - 127.0.0.1:64738:64738/udp
